# 环境准备

## 基础组件

### Python 3.11

open3d 目前只支持到 python 3.11

```
conda create -n open3d python=3.11
```

### Open3d

```
pip install open3d
```

安装了如何组件：

Successfully installed Flask-3.0.3 Jinja2-3.1.4 MarkupSafe-3.0.2 asttokens-3.0.0 attrs-24.2.0 blinker-1.9.0 certifi-2024.8.30 charset-normalizer-3.4.0 click-8.1.7 colorama-0.4.6 comm-0.2.2 configargparse-1.7 dash-2.18.2 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 decorator-5.1.1 executing-2.1.0 fastjsonschema-2.21.1 idna-3.10 importlib-metadata-8.5.0 ipython-8.30.0 ipywidgets-8.1.5 itsdangerous-2.2.0 jedi-0.19.2 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 jupyter-core-5.7.2 jupyterlab-widgets-3.0.13 matplotlib-inline-0.1.7 nbformat-5.10.4 nest-asyncio-1.6.0 numpy-2.2.0 open3d-0.18.0 packaging-24.2 parso-0.8.4 platformdirs-4.3.6 plotly-5.24.1 prompt_toolkit-3.0.48 pure-eval-0.2.3 pygments-2.18.0 pywin32-308 referencing-0.35.1 requests-2.32.3 retrying-1.3.4 rpds-py-0.22.3 six-1.17.0 stack_data-0.6.3 tenacity-9.0.0 traitlets-5.14.3 typing-extensions-4.12.2 urllib3-2.2.3 wcwidth-0.2.13 werkzeug-3.0.6 widgetsnbextension-4.0.13 zipp-3.21.0


# 代码测试

## 基础

### 判断是否安装成功

In [2]:
import os
import open3d as o3d

PATH = os.getenv('PATH')
CUDA_PATH = os.getenv('CUDA_PATH')
CUDA_VISIBLE_DEVICES = os.getenv('CUDA_VISIBLE_DEVICES')

print(f'PATH: "{PATH}"')
print(f'CUDA_PATH: "{CUDA_PATH}"')
print(f'CUDA_VISIBLE_DEVICES: {CUDA_VISIBLE_DEVICES}')

print(o3d.__version__)
print(o3d.__DEVICE_API__)

# set as CUDA
o3d.core.Device("cuda:0")
print(o3d.__DEVICE_API__)

PATH: "c:\Users\zhong\anaconda3\envs\open3d;C:\Users\zhong\anaconda3\envs\open3d;C:\Users\zhong\anaconda3\envs\open3d\Library\mingw-w64\bin;C:\Users\zhong\anaconda3\envs\open3d\Library\usr\bin;C:\Users\zhong\anaconda3\envs\open3d\Library\bin;C:\Users\zhong\anaconda3\envs\open3d\Scripts;C:\Users\zhong\anaconda3\envs\open3d\bin;C:\Users\zhong\anaconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files\dotnet;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;Z:\Service\Flutter\flutter_windows_3.24.5-stable\flutter\bin;C:\Users\zhong\AppData\Local\Microsoft\WindowsApps;C:\Users\zhong\.dotnet\tools;Z:\Service\Java\jvms;Z:\Service\Java\jdk-1.8\bin;C:\Users\zhong\AppData\Roaming\nvm;C:\Program Files\nodejs;c:\Users\zhong\AppData\L

### 补充安装 jupyter 的 nbextensions 组件

Ref: https://stackoverflow.com/questions/49647705/jupyter-nbextensions-does-not-appear

```
pip install jupyter_contrib_nbextensions
```

用下面的安装方式：

```
jupyter contrib nbextension install --user

# > use this
conda install -c conda-forge jupyter_contrib_nbextensions
jupyter contrib nbextension install --sys-prefix

jupyter nbextension enable --py widgetsnbextension --sys-prefix

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok
```

前面只在命令行中处理，还不行，还要在 juypter 环境内，执行一下。

应该是需要在特定运行的环境中启用 ipywidgets 才行。

In [1]:
!jupyter nbextension enable --py widgetsnbextension --sys-prefix

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok


In [1]:
import ipywidgets as widgets
from IPython.display import display

button = widgets.Button(description="Click me")
display(button)

Button(description='Click me', style=ButtonStyle())

### 显示点云数据

<img src="assets/screen_capture/Weixin%20Screenshot_20241211114757.png" width="600">

控制按键： R N + - Shift Alt Ctrl

In [10]:
import open3d as o3d
import numpy as np

print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)
print(pcd)
print(np.asarray(pcd.points))

# 折腾完！官方给的下面的例子，其它参数不能使用，全部注释掉了。
o3d.visualization.draw_geometries(
    [pcd],
    # zoom=0.3412,
    # front=[0.4257, -0.2125, -0.8795],
    # lookat=[2.6172, 2.0475, 1.532],
    # up=[-0.0694, -0.9768, 0.2024]
)

Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


### 体素（Voxel）采样并显示

<img src="assets/screen_capture/Weixin Screenshot_20241211115604.png" width="600">

In [11]:
import open3d as o3d
import numpy as np

print("Downsample the point cloud with a voxel of 0.05")

ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

downpcd = pcd.voxel_down_sample(voxel_size=0.05)

o3d.visualization.draw_geometries(
    [downpcd],
    # zoom=0.3412,
    # front=[0.4257, -0.2125, -0.8795],
    # lookat=[2.6172, 2.0475, 1.532],
    # up=[-0.0694, -0.9768, 0.2024]
)

Downsample the point cloud with a voxel of 0.05


### 显示法线

<img src="assets/screen_capture/Weixin Screenshot_20241211120127.png" width="600">


In [3]:
import open3d as o3d
import numpy as np

print("Recompute the normal of the downsampled point cloud")

ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

downpcd = pcd.voxel_down_sample(voxel_size=0.03)

downpcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

o3d.visualization.draw_geometries(
    [downpcd],
    # zoom=0.3412,
    # front=[0.4257, -0.2125, -0.8795],
    # lookat=[2.6172, 2.0475, 1.532],
    # up=[-0.0694, -0.9768, 0.2024],
    point_show_normal=True
)


Recompute the normal of the downsampled point cloud


### 沿所选区域截取

<img src="assets/screen_capture/Weixin Screenshot_20241211122951.png" width="600">

In [1]:
import open3d as o3d
import numpy as np

print("Load a polygon volume and use it to crop the original point cloud")

demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)

# 框选选择
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)
chair = vol.crop_point_cloud(pcd)

# # 源始数据水平移动
# transformation_matrix = np.identity(4)
# transformation_matrix[0, 3] = 10
# pcd.transform(transformation_matrix)
# merge = pcd + chair

# TODO: 应该可以还能显示框选的范围

o3d.visualization.draw_geometries(
    [chair],
    # zoom=0.7,
    # front=[0.5439, -0.2333, -0.8060],
    # lookat=[2.4615, 2.1331, 1.338],
    # up=[-0.1781, -0.9708, 0.1608]
)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Load a polygon volume and use it to crop the original point cloud


### 上颜色（报错）

In [ ]:
import open3d as o3d
import numpy as np

demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)

# 框选选择
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)
chair = vol.crop_point_cloud(pcd)

# 加颜色
chair.paint_uniform_color([1, 0.706, 0])

o3d.visualization.draw_geometries([chair])

### 距离

<img src="assets/screen_capture/Weixin Screenshot_20241211124623.png" width="600">

In [2]:
import open3d as o3d
import numpy as np

demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)

# 获取框选出来的椅子
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)
chair = vol.crop_point_cloud(pcd)

# 计算出每个点到椅子的“最短”距离
dists = pcd.compute_point_cloud_distance(chair)
dists = np.asarray(dists)

# 选出距离 > 1cm 的点
ind = np.where(dists > 0.01)[0]

pcd_without_chair = pcd.select_by_index(ind)

o3d.visualization.draw_geometries([pcd_without_chair])

### 画边界体积 Bounding volumes (有错误)

In [2]:
import open3d as o3d
import numpy as np

demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)

# 获取框选出来的椅子
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)
chair = vol.crop_point_cloud(pcd)

aabb = chair.get_axis_aligned_bounding_box()
# 不让设置颜色 报错： [WinError 10054] An existing connection was forcibly closed by the remote host
# aabb.color = (1, 0, 0)

obb = chair.get_oriented_bounding_box()
# 不让设置颜色 报错： [WinError 10054] An existing connection was forcibly closed by the remote host
# obb.color = (0, 1, 0)

o3d.visualization.draw_geometries([chair, aabb, obb])

### 最小凸集

<img src="assets/screen_capture/Weixin Screenshot_20241211132248.png" width="600">

In [7]:
import open3d as o3d
import numpy as np

bunny = o3d.data.BunnyMesh()
mesh = o3d.io.read_triangle_mesh(bunny.path)
mesh.compute_vertex_normals()

pcl = mesh.sample_points_poisson_disk(number_of_points=2000)

hull, _ = pcl.compute_convex_hull()
hull_ls = o3d.geometry.LineSet.create_from_triangle_mesh(hull)

# hull_ls.paint_uniform_color((1, 0, 0))

o3d.visualization.draw_geometries([pcl, hull_ls])

### DBSCAN 聚类

给定一个点云，例如来自深度传感器，我们希望将局部点云簇分组在一起。为此，我们可以使用聚类算法。Open3D 实现了 DBSCAN [Ester1996]，它是一种基于密度的聚类算法。该算法在 cluster_dbscan 中实现，需要两个参数： eps 定义簇中邻居的距离， min_points 定义形成簇所需的最小点数。函数返回 labels ，其中标签 -1 表示噪声。

In [2]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array(
        pcd.cluster_dbscan(eps=0.02, min_points=10, print_progress=True)
    )

max_label = labels.max()

print(f"point cloud has {max_label + 1} clusters")

colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0

# 不让设置颜色
# pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])

o3d.visualization.draw_geometries([pcd])

print(f"completed")

[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 10
point cloud has 10 clusters


### Plane segmentation 飞机分割

<img src="assets/screen_capture/Weixin Screenshot_20241211134711.png" width="600">
<img src="assets/screen_capture/Weixin Screenshot_20241211134859.png" width="600">

In [1]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

pcd_point_cloud = o3d.data.PCDPointCloud()
pcd = o3d.io.read_point_cloud(pcd_point_cloud.path)

plane_model, inliers = pcd.segment_plane(distance_threshold=0.01,
                                         ransac_n=3,
                                         num_iterations=1000)

[a, b, c, d] = plane_model

print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")

inlier_cloud = pcd.select_by_index(inliers)

# 不让设置颜色
# inlier_cloud.paint_uniform_color([1.0, 0, 0])

outlier_cloud = pcd.select_by_index(inliers, invert=True)

o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud],)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Plane equation: -0.06x + -0.10y + 0.99z + -1.06 = 0


### Planar patch detection 平面补丁检测 （报错）

除了找到具有最大支撑的单个平面外，Open3D 还包括一个使用基于稳健统计方法的平面补丁检测算法[ArujoAndOliveira2020]。此算法首先将点云细分为更小的块（使用八叉树），然后尝试将平面拟合到每个块。如果平面通过稳健的平面性测试，则被接受。通过取中点位置和中点法线来拟合一个子集的点的平面，并估计一个平面 
 。稳健的平面性检查包括两个主要组件。首先，找到每个点法线与拟合平面法线之间的角度分布。如果这个分布的扩散太大（即所有相关点法线之间的方差太大），则拒绝该平面。其次，计算从拟合平面到每个点的距离分布。如果使用共面性度量（参见[ArujoAndOliveira2020]的第 4 图）测量的这个分布的扩散太大，则拒绝该平面。 在找到一组初始飞机后，使用迭代过程将飞机增长和合并成更小、更稳定的飞机集合。然后可以使用它们相关点集的二维凸包来界定这些飞机，并提取平面补片。

In [ ]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

dataset = o3d.data.PCDPointCloud()
pcd = o3d.io.read_point_cloud(dataset.path)
assert (pcd.has_normals())

# using all defaults
oboxes = pcd.detect_planar_patches(
    normal_variance_threshold_deg=60,
    coplanarity_deg=75,
    outlier_ratio=0.75,
    min_plane_edge_length=0,
    min_num_points=0,
    search_param=o3d.geometry.KDTreeSearchParamKNN(knn=30))

print("Detected {} patches".format(len(oboxes)))

geometries = []
for obox in oboxes:
    mesh = o3d.geometry.TriangleMesh.create_from_oriented_bounding_box(obox, scale=[1, 1, 0.0001])
    mesh.paint_uniform_color(obox.color)
    geometries.append(mesh)
    geometries.append(obox)
geometries.append(pcd)

o3d.visualization.draw_geometries(geometries,)

### Hidden point removal 隐藏点去除

想象您想从一个给定的视点渲染点云，但由于背景中的点没有被其他点遮挡，这些点会泄露到前景中。为此，我们可以应用一个隐藏点去除算法。在 Open3D 中，实现了[Katz2007]的方法，该方法在不进行表面重建或法线估计的情况下，近似计算从给定视点观察点云的可见性。

<img src="assets/screen_capture/Weixin Screenshot_20241211140027.png" width="600" />

In [2]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

print("Convert mesh to a point cloud and estimate dimensions")
armadillo = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo.path)
mesh.compute_vertex_normals()

pcd = mesh.sample_points_poisson_disk(5000)
diameter = np.linalg.norm(
    np.asarray(pcd.get_max_bound()) - np.asarray(pcd.get_min_bound()))
o3d.visualization.draw_geometries([pcd])

Convert mesh to a point cloud and estimate dimensions


In [3]:
print("Define parameters used for hidden_point_removal")
camera = [0, 0, diameter]
radius = diameter * 100

print("Get all points that are visible from given view point")
_, pt_map = pcd.hidden_point_removal(camera, radius)

print("Visualize result")

pcd = pcd.select_by_index(pt_map)

o3d.visualization.draw_geometries([pcd])

: 